### ISSUE TITLE
Can't connect on Firefox

### ISSUE THREAD

**Issue by georgejkaye** [ObsidianEagle/pile-of-fire#4] opened 2021-01-18 22:01 UTC
Cannot make/join games on Firefox, returns error 1006.

**Comment by ObsidianEagle** [comment] 2021-01-18 23:44
Fixed in the latest main.

Problem was caused by not preventing default form submit behaviour when creating/joining a room; Odd that that has different behaviour between Chrome and Firefox.

**Closed as completed by ObsidianEagle** 2021-01-18 23:44 UTC
